### ISSUE TITLE
forwarders template doesn't work with example

### ISSUE THREAD

**Issue by dullyouth** [sous-chefs/unbound#26]
It looks like the forwarders template takes the literal value of the arrays without properly parsing it, causing the config to be invalid and fail.

I'm trying to pass an array of ips for an individual domain, which it looks like no longer works with v 1.0.0 of this cookbook.

```
# output of trying to start unbound with the example.
 service unbound reload
 * Reloading recursive DNS server unbound                                       No process in pidfile '/var/run/unbound.pid' found running; none killed.
                                                                         [fail]
root@dokken:/# service unbound restart
 * Restarting recursive DNS server unbound                                      /etc/unbound/unbound.conf.d/forward-zone.conf:21: error: unknown keyword '10.1.1.202'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: stray '"'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: unknown keyword ','
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: stray '"'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: unknown keyword '10.1.1.203'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: stray '"'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: unknown keyword ']'
/etc/unbound/unbound.conf.d/forward-zone.conf:21: error: stray '"'
read /etc/unbound/unbound.conf failed: 8 errors in configuration file
```

```
#config on the machine
/etc/unbound/unbound.conf.d# cat forward-zone.conf
# Generated by Chef for dokken
#
# Forward zones
# Create entries like below, to make all queries for 'example.com' and
# 'example.org' go to the given list of servers. These servers have to handle
# recursion to other nameservers. List zero or more nameservers by hostname
# or by ipaddress. Use an entry with name "." to forward all queries.
# forward-zone:
#   name: "example.com"
#   forward-addr: 192.0.2.68
#   forward-addr: 192.0.2.73@5355  # forward to port 5355.
# forward-zone:
#   name: "example.org"
#   forward-host: fwd.example.com
server:
  forward-zone:
    name: "forward.example.com."
    forward-addr: "10.1.1.201"
  forward-zone:
    name: "forward2.example.com."
    forward-host: "["10.1.1.202", "10.1.1.203"]"
  forward-zone:
    name: "forward3.example.com."
    forward-host: "ns1.none"
```

```
# chef code
unbound_configure 'config' do
  local_zone 'id' => 'int_dummy_domain',
             'ns' => [{ 'dummy.com' => '127.0.0.1' }],
             'host' => [{ 'dummy.com' => '10.1.1.200' }]

#  forward_zone forwarder_zones
forward_zone 'forward1' => [{ 'forward.example.com' => '10.1.1.201' }],
              'forward2' => [{ 'forward2.example.com' => ['10.1.1.202', '10.1.1.203'] }],
              'forward3' => [{ 'forward3.example.com' => 'ns1.none' }]
  num_threads 2
  enable_ipv4 true
  enable_ipv6 true
  enable_tcp true
  enable_udp true
  access_control '127.0.0.1/8' => 'allow',
                 '0.0.0.0/0' => 'refuse'
  use_syslog 'yes'
  stats_interval 1
  stats_cumulative 'yes'
  stats_extended 'yes'
end
```
